import streamlit as st
import pandas as pd
from pathlib import Path

st.set_page_config(page_title="PCB Inspection History",layout="wide")
st.title("PCB Inspection History")
st.caption("Inspection records generated by the live PCB inspection API")
FILE=Path("runs/inspection_reports/inspection_history.csv")
if not FILE.exists():
    st.warning("No inspection history found.")
    st.stop()
df=pd.read_csv(FILE)
real=df[df["status"].isin(["PASS","FAIL"])]
total=len(real)
passes=int((real["status"]=="PASS").sum())
fails=int((real["status"]=="FAIL").sum())
defects=int((real["defect"]!="NONE").sum())
c1,c2,c3,c4=st.columns(4)
c1.metric("Inspections",total)
c2.metric("PASS",passes)
c3.metric("FAIL",fails)
c4.metric("Defects",defects)
st.subheader("Defect Distribution")
counts=real[real["defect"]!="NONE"]["defect"].value_counts()
if len(counts)>0: st.bar_chart(counts)
else: st.info("No defects recorded yet.")
st.subheader("Latest Inspection Records")
st.dataframe(real.sort_values("timestamp",ascending=False),width="stretch")
st.download_button("Download Inspection History CSV",data=FILE.read_bytes(),file_name="inspection_history.csv",mime="text/csv")